"use client";
import {useState} from "react";
import candidates from "../data/candidates.json";

export default function Home(){
 const [candidateId,setCandidateId]=useState("CAND-003"); const [sessionId,setSessionId]=useState(() => `${Date.now()}-${Math.random().toString(36).slice(2)}`);
 const [messages,setMessages]=useState<{role:string;content:string}[]>([]); const [input,setInput]=useState(""); const [done,setDone]=useState(false); const [feedback,setFeedback]=useState<any>(null); const [loading,setLoading]=useState(false);
 async function send(){ if(loading)return; setLoading(true); try{ const payload=messages.length===0?{sessionId,candidate:(candidates as any).candidates.find((c:any)=>c.member.id===candidateId)}:{sessionId,message:input}; const r=await fetch("/api/interview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const d=await r.json(); if(!r.ok)throw new Error(d.error); if(messages.length>0)setMessages(m=>[...m,{role:"candidate",content:input}]); setMessages(m=>[...m,{role:"assistant",content:d.reply}]); setInput(""); setDone(d.done); setFeedback(d.feedback||null);}catch(e:any){setMessages(m=>[...m,{role:"error",content:e.message}]);}finally{setLoading(false)} }
 function reset(){setSessionId(`${Date.now()}-${Math.random().toString(36).slice(2)}`);setMessages([]);setDone(false);setFeedback(null);setInput("")}
 return <main><header><div><span className="eyebrow">INTERVAI · AI COHORT</span><h1>AI Interview Agent</h1><p>Adaptive technical interview grounded in the candidate’s 31-day learning journey.</p></div><div className="pill">{done?"Interview complete":"Live interview"}</div></header><section className="layout"><aside><label>Candidate</label><select value={candidateId} onChange={e=>{setCandidateId(e.target.value);reset()}}>{(candidates as any).candidates.map((c:any)=><option key={c.member.id} value={c.member.id}>{c.member.name} · {c.member.jobRole}</option>)}</select><button onClick={reset}>New interview</button><div className="card"><b>Agent behavior</b><ul><li>8+ questions</li><li>4+ curriculum days</li><li>Context-aware follow-ups</li><li>Structured final feedback</li></ul></div></aside><div className="chat"><div className="messages">{messages.length===0?<div className="empty"><h2>Ready when you are.</h2><p>Start the interview to get a candidate-specific technical question.</p><button onClick={send}>Start interview</button></div>:messages.map((m,i)=><div key={i} className={m.role}><span>{m.role==='assistant'?'Interviewer':m.role==='candidate'?'You':'System'}</span><p>{m.content}</p></div>)}</div>{feedback&&<div className="feedback"><h2>Interview feedback</h2><p>{feedback.summary}</p><div className="cols"><div><b>Strengths</b>{feedback.strengths.map((x:string)=><div key={x}>✓ {x}</div>)}</div><div><b>Gaps</b>{feedback.gaps.map((x:string)=><div key={x}>• {x}</div>)}</div><div><b>Next</b>{feedback.next.map((x:string)=><div key={x}>→ {x}</div>)}</div></div></div>}{!done&&messages.length>0&&<form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Explain your reasoning…" disabled={loading}/><button disabled={loading||!input.trim()}>{loading?"Thinking…":"Send"}</button></form>}</div></section></main>
}
